# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: it is sample project
on:
 push:
   branches: "main"
 pull_request:
   branches: "main"
jobs:
  build-test-deply:
   runs-on: ubuntu-latest
   steps:
    - name: code checkout
      uses: actions/checkout@v4
    - name: dotnet-version
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
        
       
 
